name: code-validation
on:
  - push
  - workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:14-alpine
    steps:
      - name: checking repository out
        uses: actions/checkout@v3

      - name: Install eslint
        run: npm i eslint

      - name: eslint validation
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    container: node:14-alpine
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: checking repository out
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: run tests
        run: npm run test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          JWT_TOKEN: JWT_TOKEN
          SALT_ROUNDS: 1