name: deployment-to-prod
on:
  - push
  - workflow_dispatch

jobs:
  upload-files:
    runs-on: ubuntu-latest
    container: node:14-alpine

    steps:
      - name: checking repository out
        uses: actions/checkout@v3

      - uses: ./.github/workflows/code-validation.yml

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: riiul.hk.tlu.ee
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 2222
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/test/**
            **/src/**
            **/files/**
            .env*
            readme.md
            tsconfig.json
            docker-compose.yml
            babel.config.js
            .eslint*
